### ISSUE TITLE
Test and refine Deepfake generation model

### ISSUE THREAD

**Issue by BasicallyOk** [BasicallyOk/deepfake-lip-sync#20]

**Comment by HueyAmiNhvtim** [comment]
Transitioned from attempting to use scipy.io.wavfile.read to convert audio to numpy to converting audio to spectrogram.

**Comment by BasicallyOk** [comment]
Generated gif does not look like an actual human face. The discriminator and generator does not seem very balanced.

**Comment by BasicallyOk** [comment]
Model is satisfactory, the discriminator seems to be at fault for weird generations
