### ISSUE TITLE
Generator's losses resulting in NaN.

### ISSUE THREAD

**Issue by HueyAmiNhvtim** [BasicallyOk/deepfake-lip-sync#36]
The generator at certain epochs will output NaN in all losses, including MaE, Adv, Disc_Loss, and Real_Loss.

**Comment by BasicallyOk** [comment]
The discriminator seems to be at fault. Strangely, this is not reproducible in Huy's batch (which at this point includes 35, 44, 49).

**Comment by BasicallyOk** [comment]
Only happen for certain batches. The models themselves being faulty is unlikely as established with #39
